{
 "title": "Harvester Capacity",
 "tags": [ "bits-custom" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pvcs",
    "label": "pvcs",
    "query": {
     "query": "query_result(group by (pvc) (longhorn_volume_actual_size_bytes))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage requested vs actual",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=~\"${pvcs}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "longhorn_volume_actual_size_bytes{pvc=~\"${pvcs}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "round(sum(kube_node_status_allocatable{resource=\"memory\"}) / 1024 / 1024 / 1024, 1)",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_requests{resource=\"memory\", node!=\"\"}) / 1024 / 1024 / 1024, 1)",
       "legendFormat": "Reserved Memory"
      },
      {
       "expr": "sum(container_memory_usage_bytes{job=\"kubelet\", image!=\"\", container!=\"POD\"}) / 1024 / 1024 / 1024",
       "legendFormat": "Used Memory"
      }
     ]
    },
    {
     "title": "CPU Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
       "legendFormat": "Total CPU"
      },
      {
       "expr": "round(sum(kube_pod_container_resource_requests{resource=\"cpu\", node!=\"\"}), 0.01)",
       "legendFormat": "Reserved CPU"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container!=\"POD\"}[5m]))",
       "legendFormat": "Used CPU (over 5m)"
      }
     ]
    },
    {
     "title": "Storage Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "tbytes" } },
     "targets": [
      {
       "expr": "sum (longhorn_node_storage_capacity_bytes) / 1024 / 1024 / 1024 / 1024",
       "legendFormat": "Total Storage (TB)"
      },
      {
       "expr": "sum(longhorn_node_storage_usage_bytes) / 1024 / 1024 / 1024 / 1024",
       "legendFormat": "Used Storage (TB)"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) / 1024 / 1024 / 1024 / 1024 * 3 ",
       "legendFormat": "Reserved Storage (TB)"
      }
     ]
    }
   ]
  },
  {
   "title": "Ausfall-Puffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "# Ausfall-Nodes (nach RAM)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(kube_node_status_allocatable{resource=\"memory\"}) \r\n  - sum(kube_pod_container_resource_requests{resource=\"memory\", node!=\"\"})\r\n)\r\n/\r\nmax(sum(kube_node_status_allocatable{resource=\"memory\"}) by (node))",
       "legendFormat": "__auto"
      },
      { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "# Ausfall-Nodes (nach CPU)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(kube_node_status_allocatable{resource=\"cpu\"}) \r\n  - sum(kube_pod_container_resource_requests{resource=\"cpu\", node!=\"\"})\r\n)\r\n/\r\nmax(sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node))\r\n",
       "legendFormat": "__auto"
      },
      { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "# Ausfall-Disks ",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(longhorn_node_storage_capacity_bytes) \r\n  - sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) * 3\r\n) / max(longhorn_disk_capacity_bytes)",
       "legendFormat": "Ausfalldisks"
      },
      {
       "expr": "count(longhorn_disk_capacity_bytes)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}