{
 "title": "Harvester VM Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "count", "label": "count", "query": "5, 10, 20" },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(${count}, (avg(rate(kubevirt_vmi_vcpu_seconds_total[5m])) by (domain, name))) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(${count}, ((kubevirt_vmi_memory_available_bytes - kubevirt_vmi_memory_unused_bytes) / kubevirt_vmi_memory_available_bytes))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage Read Traffic Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_storage_read_traffic_bytes_total[5m]))) ",
     "legendFormat": "{{name}}: {{drive}}"
    }
   ]
  },
  {
   "title": "Storage Write Traffic Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_storage_write_traffic_bytes_total[5m]))) ",
     "legendFormat": "{{name}}: {{drive}}"
    }
   ]
  },
  {
   "title": "Network Receive Bits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_network_receive_bytes_total[5m])*8))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_network_transmit_bytes_total[5m])*8))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Receive Packets (2h)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(${count}, (delta(kubevirt_vmi_network_receive_packets_total[2h])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Packets (2h)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(${count}, (delta(kubevirt_vmi_network_transmit_packets_total[2h])))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}