{
 "title": "Storage Billing",
 "tags": [ "bits-custom" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "query_result(group by (pvc_namespace) (longhorn_volume_actual_size_bytes))"
    }
   }
  ]
 },
 "panels": [
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "$cluster",
   "type": "table",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "longhorn_volume_actual_size_bytes{pvc_namespace=\"$cluster\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster Storageverbrauch (mit Clusternodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "TiB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(longhorn_volume_actual_size_bytes{pvc_namespace=\"$cluster\"}) / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster Storageverbrauch (ohne Clusternodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "TiB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(longhorn_volume_actual_size_bytes{pvc_namespace=\"$cluster\", pvc!~\"$cluster-.*\"}) / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster Storagerequest (mit Clusternodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "longhorn_volume_actual_size_bytes{pvc_namespace=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster Storagerequest (ohne Clusternodes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "longhorn_volume_actual_size_bytes{pvc_namespace=\"$cluster\", pvc!~\"$cluster-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}